"""
tools/import_from_xlsx.py — One-time bootstrap script.

Reads the ISGS_psql_Database_Proposed_Structure.xlsx spreadsheet and generates
a YAML field-mapping file for completion_reports.

Re-run this whenever the spreadsheet is updated to regenerate the YAML,
then review the diff before committing.

Usage:
    python pg_sync/tools/import_from_xlsx.py \\
        --xlsx /path/to/ISGS_psql_Database_Proposed_Structure.xlsx \\
        --sheet ISGS_WCR_Interp \\
        --out pg_sync/field_mappings/isgs/completion_reports.yaml
"""
import argparse
import sys
from collections import defaultdict
from pathlib import Path

try:
    import openpyxl
    import yaml
except ImportError:
    print("ERROR: Install dependencies with: pip install openpyxl pyyaml")
    sys.exit(1)


# Child table names to use for OGRRE Table-type parent fields
CHILD_TABLE_MAP: dict[str, str] = {
    "Type_Of_Logs":                                 "completion_report_logs",
    "Completion_For_Production":                    "completion_report_completion_intervals",
    "Gun_Perforating_Windows":                      "completion_report_gun_perforating_windows",
    "Acid_Or_Shooting_Record_Or_Fracture_Treatment": "completion_report_acid_records",
    "Casing_Record":                                "completion_report_casing_records",
    "Casing_And_Tubing_Record":                     "completion_report_casing_records",
    "Packer":                                       "completion_report_logs",  # maps to logs via packer subfields
}

INTERVAL_FIELDS: dict[str, dict] = {
    "Completion_For_Production::Open_Hole_Interval": {
        "from_col": "open_hole_from",
        "to_col":   "open_hole_to",
        "raw_col":  "open_hole_interval",
    },
    "Completion_For_Production::Perforation_Interval": {
        "from_col": "perf_from",
        "to_col":   "perf_to",
        "raw_col":  "perf_int",
    },
    "Gun_Perforating_Windows": {
        "from_col": "perf_from",
        "to_col":   "perf_to",
        "raw_col":  "perf_int",
    },
    "Interval_Cored": {
        "from_col": None,
        "to_col":   None,
        "raw_col":  "cored_interval",
    },
}


def parse_sheet(ws) -> list[dict]:
    rows = list(ws.iter_rows(values_only=True))
    records = []
    for row in rows[1:]:   # skip header row
        if not any(v for v in row):
            continue
        records.append({
            "processor":     row[0],
            "ogrre_name":    row[1],
            "pg_column":     row[2],
            "pg_type":       row[3],
            "description":   row[4],
            "units":         row[5],
            "master_table":  row[6],
            "master_field":  row[7],
            "note":          row[11] if len(row) > 11 else None,
        })
    return records


def build_mapping(records: list[dict]) -> dict:
    by_proc: dict[str, dict] = defaultdict(dict)
    child_map: dict[str, dict] = defaultdict(lambda: defaultdict(dict))

    for r in records:
        proc    = r.get("processor")
        ogrre   = r.get("ogrre_name")
        pg_col  = r.get("pg_column")

        if not proc or not ogrre or not pg_col:
            continue

        if "::" in ogrre:
            parent, child = ogrre.split("::", 1)
            child_map[proc][parent][child] = pg_col
        else:
            by_proc[proc][ogrre] = pg_col

    output = {
        "description": (
            "Maps OGRRE processor field names to PostgreSQL columns.\n"
            "Generated by tools/import_from_xlsx.py — edit YAML directly going forward."
        ),
        "target_schema": "isgs",
        "target_table":  "completion_reports",
        "child_tables":  CHILD_TABLE_MAP,
        "interval_fields": INTERVAL_FIELDS,
        "processors": {},
    }

    for proc, fields in by_proc.items():
        proc_entry: dict = {"scalar_fields": dict(fields)}
        if proc in child_map:
            proc_entry["child_fields"] = {
                parent: dict(subfields)
                for parent, subfields in child_map[proc].items()
            }
        output["processors"][proc] = proc_entry

    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Import XLSX field mapping to YAML.")
    parser.add_argument("--xlsx",  required=True, help="Path to the .xlsx file")
    parser.add_argument("--sheet", default="ISGS_WCR_Interp", help="Sheet name")
    parser.add_argument("--out",   required=True, help="Output YAML path")
    args = parser.parse_args()

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    if args.sheet not in wb.sheetnames:
        print(f"ERROR: Sheet '{args.sheet}' not found. Available: {wb.sheetnames}")
        sys.exit(1)

    ws = wb[args.sheet]
    records = parse_sheet(ws)
    mapping = build_mapping(records)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        yaml.dump(mapping, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Written {len(records)} mapping rows to {out_path}")
    proc_count = len(mapping["processors"])
    for proc, data in mapping["processors"].items():
        scalar_n = len(data.get("scalar_fields", {}))
        child_n  = sum(len(v) for v in data.get("child_fields", {}).values())
        print(f"  {proc}: {scalar_n} scalar fields, {child_n} child subfields")


if __name__ == "__main__":
    main()
