services:
  web:
    image: michaelpescelbl/orphaned-wells-ui-server:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - COLLABORATOR=${COLLABORATOR}
      - BACKEND_URL=${BACKEND_URL}
      - LOCATION=${LOCATION}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_NAME=${DB_NAME}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_SERVICE_KEY=${STORAGE_SERVICE_KEY}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - token_uri=${token_uri}
      - client_id=${client_id}
      - client_secret=${client_secret}
      - LOG_DIR=/logs
    container_name: web
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - ./logs:/logs
      - ./secrets/creds.json:/code/ogrre/creds.json:ro
      - ./secrets/michael2-service-key.json:/code/ogrre/michael2-service-key.json:ro
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
  
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/${ENVIRONMENT}:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=mpesce@lbl.gov
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: certbot
