# pthon version
FROM python:3.12

# the directory where the code will be stored inside docker container
WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./setup.py /code/setup.py
COPY ./README.md /code/README.md
COPY ./ogrre /code/ogrre

RUN pip install --no-cache-dir --no-deps --upgrade .

EXPOSE 8001

# run app in prod
CMD ["python", "ogrre/main.py", "--docker"]
