# HTTP server - only for ACME challenges and redirect
server {
    listen 80;
    listen [::]:80;

    server_name newts-server.uow-carbon.org;

    # Serve ACME challenge files from the shared "certbot-webroot" folder
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server - main app
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name newts-server.uow-carbon.org;

    client_max_body_size 100m;

    # turn off buffering for download records endpoint
    # this can have very large amounts of data which an max out the nginx cache if we have buffering on
    location ^~ /download_records/ {
        proxy_pass http://web:8001;
        proxy_buffering off;
        proxy_request_buffering off;  # this is for uploads - not really necessary
        proxy_read_timeout 180s;
        proxy_connect_timeout 180s;
        proxy_send_timeout 180s;
        send_timeout 180s;
        client_body_timeout 180s;
    }

    location / {
        proxy_pass http://web:8001;
        proxy_read_timeout 180s;
        proxy_connect_timeout 180s;
        proxy_send_timeout 180s;
        send_timeout 180s;
        client_body_timeout 180s;
    }

    # SSL certs from the shared letsencrypt volume
    ssl_certificate /etc/letsencrypt/live/newts-server.uow-carbon.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/newts-server.uow-carbon.org/privkey.pem;

    # Recommended SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers on;

    # Helps with renewal reliability
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
}