
name: Deploy OSAGE Server

on:
  push:
    branches: [osage]

jobs:
  deploy_osage:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: ./.github/workflows/deploy-dispatch.yml
    with:
      DEPLOY_ENV: osage
    secrets: inherit
