
name: Deploy ISGS Server

on:
  push:
    branches: [isgs]

jobs:
  deploy_isgs:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui-server'
    uses: ./.github/workflows/deploy-dispatch.yml
    with:
      DEPLOY_ENV: isgs
    secrets: inherit
